### ISSUE TITLE
[naviluagenerator] i can't compile on latest git

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/StaffPlugins#6]
`       CC      naviluagenerator.c
naviluagenerator.c: In function ‘atcommand_createnavigationlua_sub_warp’:
naviluagenerator.c:450:69: error: invalid type argument of ‘->’ (have ‘const struct view_data’)
  fprintf(fp_link, OUT_INDENT OUT_INDENT "%d," OUT_SEPARATOR, (nd->vd->class == WARP_CLASS) ? 99999 : nd->vd->class);
                                                                     ^
naviluagenerator.c:450:108: error: invalid type argument of ‘->’ (have ‘const struct view_data’)
  fprintf(fp_link, OUT_INDENT OUT_INDENT "%d," OUT_SEPARATOR, (nd->vd->class == WARP_CLASS) ? 99999 : nd->vd->class);
                                                                                                            ^
make[1]: *** [../../plugins/naviluagenerator.so] Error 1
`

**Comment by MishimaHaruna** [comment]
Fixed, thank you!

**Comment by tlacson7** [comment]
wow very fast . thank you Haru
